<Center><h1 style="color:DodgerBlue;">Numpy Assignment</h1></center>
<h2><p><u style="color:Tomato;">Name</u><span style="color:Tomato;">:</span> Utsab Dutta &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u style="color:Tomato;">Email</u><span style="color:Tomato;">:</span> utsabdutta1996@gmail.com &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u style="color:Tomato;">Phone</u><span style="color:Tomato;">:</span> +91-9739244583</p></h2>

<h3 style="color:Red;">Problem 1:</h3>
<p><b>Write a function so that the columns of the output matrix are powers of the input vector.</b></p>
<p>The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.</p>
<p><b>HINT:</b> Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.</p>

In [1]:
#importing Package
import numpy as np

In [16]:
#Initial Input
list_value = [1, 2, 3, 4, 5]
N = 3
increasing = True

In [17]:
#Main Logic for Theophile Vandermonde
def theophileVandermonde(list_value, N = len(list_value), increasing = False):
    list_value = np.array(list_value).reshape(-1, 1)
    temp_list_value = []
    if not increasing:
        for index in range(N - 1, -1, -1):
            temp_list_value.append(list_value ** index)
    else:
        for index in range(N):
            temp_list_value.append(list_value ** index)
    final_list_value = []
    for index in range(int(np.array(temp_list_value).size/N)):
        final_list_value.append(list(np.core.records.fromarrays(np.array(temp_list_value)[:, index]).tolist()[0]))
    return np.array(final_list_value)

In [18]:
#Calling Theophile Vandermonde with only list
print(theophileVandermonde(list_value))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [5]:
#Calling Theophile Vandermonde with only list and increasing = True
print(theophileVandermonde(list_value, increasing = increasing))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [6]:
#Calling Theophile Vandermonde with only list and N = 3
print(theophileVandermonde(list_value, N))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


In [7]:
#Calling Theophile Vandermonde with only list, N = 3 and increasing = True
print(theophileVandermonde(list_value, N, increasing = increasing))

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


<h3 style="color:Red;">Problem 2:</h3>
<h3><u>Problem Statement</u></h3>
<p><b>Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:</b></p>
<p>The moving average sequence has n-k+1 elements as shown below.</p>
<p>The moving averages with k=4 of a ten-value sequence (n=10) is shown below</p>
<p>i 1 2 3 4 5 6 7 8 9 10</p>
<p>===============</p>
<p>Input 10 20 30 40 50 60 70 80 90 100</p>
<p>y1 25 = (10+20+30+40)/4</p>
<p>y2 35 = (20+30+40+50)/4</p>
<p>y3 45 = (30+40+50+60)/4</p>
<p>y4 55 = (40+50+60+70)/4</p>
<p>y5 65 = (50+60+70+80)/4</p>
<p>y6 75 = (60+70+80+90)/4</p>
<p>y7 85 = (70+80+90+100)/4</p>
<p>Thus, the moving average sequence has n-k+1=10-4+1=7 values.</p>
<p><b>Question:</b> Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.</p>

In [8]:
#importing Package
import numpy as np

In [9]:
#Input Type 1
list_value = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3

In [10]:
#Main Logic for Moving Average
def movingAverage(list_value, window):
    list_value = np.array(list_value)
    for index in range(len(list_value) - window + 1):
        yield np.sum(list_value[index:index+window])/window

In [11]:
#Calling Moving Average for Input Type 1
print(f'The moving averages with k={window} of a (n={len(list_value)})-value sequence is shown below:')
for index, average in enumerate(movingAverage(list_value, window)):
    print(f'Y[{index + 1}]: {np.round(average,2)}')
print(f'Thus, the moving average sequence has {len(list_value) - window + 1} values.')

The moving averages with k=3 of a (n=13)-value sequence is shown below:
Y[1]: 5.0
Y[2]: 4.67
Y[3]: 5.67
Y[4]: 6.67
Y[5]: 9.67
Y[6]: 28.67
Y[7]: 49.33
Y[8]: 72.67
Y[9]: 84.0
Y[10]: 93.33
Y[11]: 116.33
Thus, the moving average sequence has 11 values.


In [12]:
#Input Type 2
list_value = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
window = 4

In [13]:
#Calling Moving Average for Input Type 2
print(f'The moving averages with k={window} of a (n={len(list_value)})-value sequence is shown below:')
for index, average in enumerate(movingAverage(list_value, window)):
    print(f'Y[{index + 1}]: {np.round(average,2)}')
print(f'Thus, the moving average sequence has {len(list_value) - window + 1} values.')

The moving averages with k=4 of a (n=10)-value sequence is shown below:
Y[1]: 25.0
Y[2]: 35.0
Y[3]: 45.0
Y[4]: 55.0
Y[5]: 65.0
Y[6]: 75.0
Y[7]: 85.0
Thus, the moving average sequence has 7 values.
